import Foundation

public enum ContentType: String {
    case javaArchive = "application/java-archive"
    case ediX12 = "application/EDI-X12"
    case edifact = "application/EDIFACT"
    case js = "application/javascript"
    case octetStream = "application/octet-stream"
    case ogg = "application/ogg"
    case pdf = "application/pdf"
    case xhtml = "application/xhtml+xml"
    case shockwave = "application/x-shockwave-flash"
    case json = "application/json"
    case ldJson = "application/ld+json"
    case xml = "application/xml"
    case zip = "application/zip"
    case formUrlencoded = "application/x-www-form-urlencoded"
    case mpegAudio = "audio/mpeg"
    case wma = "audio/x-ms-wma"
    case realAudio = "audio/vnd.rn-realaudio"
    case wav = "audio/x-wav"
    case gif = "image/gif"
    case jpeg = "image/jpeg"
    case png = "image/png"
    case tiff = "image/tiff"
    case msIcon = "image/vnd.microsoft.icon"
    case xIcon = "image/x-icon"
    case djvu = "image/vnd.djvu"
    case svg = "image/svg+xml"
    case multipartMixed = "multipart/mixed"
    case multipartAlternative = "multipart/alternative"
    case multipartRelated = "multipart/related"
    case multipartFormData = "multipart/form-data"
    case css = "text/css"
    case csv = "text/csv"
    case html = "text/html"
    case jsObsolete = "text/javascript"
    case plain = "text/plain"
    case textXml = "text/xml"
    case mpegVideo = "video/mpeg"
    case mp4 = "video/mp4"
    case quicktime = "video/quicktime"
    case wmv = "video/x-ms-wmv"
    case xMsVideo = "video/x-msvideo"
    case flv = "video/x-flv"
    case webm = "video/webm"
}

